spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intern
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
server:
  port: 8080
flyway:
  url: jdbc:postgresql://localhost:5432/intern
  schemas: public
  user: postgres
  password: postgres
springdoc:
  enable-native-support: true
  swagger-ui.path: /swagger-ui

