###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
PUT http://localhost:8080/users/1
Content-Type: application/json

{
  "login": "SUPER ADMIN"
}

###
POST http://localhost:8080/users/
Content-Type: application/json

{
  "login": "SUPER ADMIN"
}


###
GET http://localhost:8080/tasks

###
GET http://localhost:8080/tasks/1


###
GET http://localhost:8080/tasks/release/1


###
DELETE http://localhost:8080/tasks/1

###
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "id": 100,
  "title": "Приложение использует ресурсные файлы локализации",
  "status": "BACKLOG",
  "release": 2,
  "owner": 1
}

<> 2023-03-24T211314.400.json
<> 2023-03-24T211234.400.json
<> 2023-03-24T165632.400.html
<> 2023-03-24T165607.400.html

###
GET http://localhost:8080/releases/users/

<> 2023-03-24T225031.200.json
<> 2023-03-24T165827.200.json

###
GET http://localhost:8080/releases/users/2

<> 2023-03-24T225039.400.json
<> 2023-03-24T165930.400.json
<> 2023-03-24T165847.400.json

###
GET http://localhost:8080/releases

<> 2023-03-24T165911.200.json